### ISSUE TITLE
[Suggestion] Config and Loot control

### ISSUE THREAD

**Issue by tealtoxic** [ElColoManco/Risk-of-Rain-Mod#1]
i love ror so thank you for making this mod, but can you please :
- add config to control loot probability
- add config to control spawn on certain dimension

reason : 
- my modpack need more mobs so ror seems interesting, but the infusion is too common and i want it to be admin controlled.

tried :
- i tried to extract the jar and look for loot table and its there but i dont know how to recompile after edit (teach me?)

Thank you.

**Comment by ElColoManco** [comment]
Hi Tealtoxic! As soon as I can build the config system I will add those things. I just have to investigate on how to make them!
Thanks for participating!
