### ISSUE TITLE
Server Startup Crash

### ISSUE THREAD

**Issue by Freebi85** [ElColoManco/Risk-of-Rain-Mod#2]
Hey There :) Just a server startup crash.
"Risk of Rain Mod has class loading errors"

Java Version: 1.8.0_271
forge-1.16.4-35.0.17

[crash-2020-11-14_16.24.48-fml.txt](https://github.com/ElColoManco/Risk-of-Rain-Mod/files/5540992/crash-2020-11-14_16.24.48-fml.txt)

**Comment by ElColoManco** [comment]
I just discovered why servers cannot start. It is because of the drone bullet entity registry. Apparently it should be regitered differently. I will be testing other ways

**Comment by ElColoManco** [comment]
Problem solved. RoRmod 1.1.2 is available with the server startup fix and new features
