### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by German998** [ElColoManco/Risk-of-Rain-Mod#5]
the golem attacked me, lifted me up with his hand attack and then used his "vision" to throw me away far up in the air and then the crash happened. (at that moment i was using an armor set of mutant skeleton from (mutant creatures) that gives me jump boost, dunno if that info helps)
[crash-2021-01-16_11.57.08-server.txt](https://github.com/ElColoManco/Risk-of-Rain-Mod/files/5824602/crash-2021-01-16_11.57.08-server.txt)

**Comment by ElColoManco** [comment]
Hey german! Thanks for the report!
That mutant  was not involved in the crash. I have not been able to find out what is causing this problem. I only have the suspicion that the golem when pushing you and losing vision with you generates problems in the ticking of the game. This will be solved in the [RoRmod 1.1.3](https://www.curseforge.com/minecraft/mc-mods/risk-of-rain-mod/files) version wich will disable the knockback effect of the laser (although you will be able to activate it again with this crash risk)

**Comment by n0itLT** [comment]
This is still happening as I just got this crash earlier today.
