### ISSUE TITLE
Bug at crowbar( and possibly other items as well)

### ISSUE THREAD

**Issue by TerranE5** [ElColoManco/Risk-of-Rain-Mod#8]
Could you make an option of stack limit in certain items? Thanks to the crowbar, I can one hit a boss with a stone shovel, A STONE SHOVEL! IN 64 STACKS!!!!!

**Comment by ElColoManco** [comment]
Well this is not a bug. RoR items at high stacks do that even in the original game. Anyway I will make a config for changing the ammount of items stacked to increase the amplifier effect (eg: +1 level every **x** stacks). Currently is 4
