### ISSUE TITLE
Bugged items on multiplayer

### ISSUE THREAD

**Issue by Lewisking50** [ElColoManco/Risk-of-Rain-Mod#9]
We have a bug on our server that causes the item effects to be shared amongst players.
Whoever logged in last is the one who shares their items and as long as a player has one of the mod items in their inventory they receive the effect of the other, irrelevant on who has the greater number.
So if Player A logs in with 64 Crowbars, Player B with 1 Crowbar receives the effect of 64 Crowbars.
Infusion, Goat Hoofs and Soldier's Syringe are not affected, Bustling Fungus stop working altogether if more than one player has them.
Not sure how or if Lens-Maker's Glasses are affected.

MC Version: 1.16.4
Forge: 35.1.37
Modpack: Mineshafts and Monsters 1.2.0

**Comment by ElColoManco** [comment]
Thanks for the report. I'll be figuring out how to correct this
